version: '3'
services:
  app:
    image: bank
    ports:
      - 8080:8080

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pastest
      POSTGRES_USER: sa
    ports:
      - 5432:5432