version: '3'
services:
  app:
    image: bank
    container_name: bank
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pastest
      POSTGRES_USER: sa
    ports:
      - 5432:5432

#docker-compose up