spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sa
    username: sa
    password: pastest
    driver-class-name: org.postgresql.Driver
#feature:
#  toggle:
#    delete:
#      client: true
